### ISSUE TITLE
Set `JAVA_HOME` and `JDK_HOME` as defaults, not overrides

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/libjvm#185]
In [Paketo RFC 0019](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0019-buildpack-set-env-vars-defaults.md), the project set the norm that 
> If a user provides a language ecosystem environment variable at build time and the buildpack typically sets an opinionated build time value, the user's value should override or have precedence over the buildpack-set value.

"Language ecosystem environment variables" are those that are respected by language ecosystem tooling, like the Java toolchain. `JAVA_HOME` and `JDK_HOME` are two of these sort of variables.

Currently, [libjvm sets these environment variables using the OVERRIDE option](https://github.com/paketo-buildpacks/libjvm/blob/9d2cc729ca0ee8c79a16b0b602e5eeb019c119dc/jdk.go#L73-L74).

I propose that these environment variables should be set with the DEFAULT option instead, to bring libjvm in alignment with the RFC. This should not change buildpack behaviour in the happy-path case. But it will allow advanced users to override the buildpack's default `JAVA_HOME` and `JDK_HOME` values at build- or launch-time

**Comment by loewenstein** [comment]
@dmikusa What about this? If you agree that libjvm should follow the spec here, we can have a look and provide a PR.

**Comment by dmikusa** [comment]
This came up previously and I don't think we should follow the spec for these particular variables. My opinion is that a user should not set these values ever, the buildpack should always set them so I think `OVERRIDE` is appropriate.

If there is a legitimate use case for setting them, I'd be OK with making the change. I just can't think of a reason. The buildpack is the only thing that will know where the JVM is installed, so it should be setting these. Even in the case where the JVM is installed as part of the stack, or by a buildpack extension, I think that the buildpack should run, pull out the location of the JVM, and set these env variables. Presently, you can't set env variables if you only publish a stack so the buildpack would still be required to get the env variables set in a consistent way.

**Comment by dmikusa** [comment]
OK. I'm going to mark this as `won't fix` for now.

If someone comes up with a legitimate reason that requires `JAVA_HOME` and/or `JDK_HOME` to be set as DEFAULT by the buildpack please raise it here and we can reconsider this change.
