### ISSUE TITLE
Failed to update CACERTS when readOnlyRootFilesystem is set

### ISSUE THREAD

**Issue by belfo** [paketo-buildpacks/libjvm#281]
## Expected Behavior
At startup it should create the new cacert in different folder (like tmp) that can be mounted with write rights

## Current Behavior
Currently it try to modify it in place
WARNING: Unable to add container CA certificates to JVM because /layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts is read-only

## Steps to Reproduce

1. Run a builded container with readOnlyRootFilesystem set to true

## Motivations

It's mandatory to use readOnlyRootFilesystem in our env

**Comment by loewenstein** [comment]
We'll likely start on a pull request for this soon.

**Comment by dmikusa** [comment]
@loewenstein - Out of curiosity, which option are you planning to implement? Or both? I think my preference would be to have both. They both seem useful, but we're thankful for any contribution.

**Comment by loewenstein** [comment]
@dmikusa Let me cite from our story :)
> There are already [two proposals for achieving this](https://github.com/paketo-buildpacks/bellsoft-liberica/issues/389#issuecomment-1499039889). Let's pick one and create a PR (or do both even - if that choice seems to make sense).

**Comment by c0d1ngm0nk3y** [comment]
> Out of curiosity, which option are you planning to implement? Or both? I think my preference would be to have both. They both seem useful, but we're thankful for any contribution.

We finally start with that :) tbh, I would prefer option 2 for 3 reasons:

1. @belfo would prefer this (see [comment](https://github.com/paketo-buildpacks/libjvm/issues/281#issuecomment-1519177522))
2. The use case described [here](https://github.com/paketo-buildpacks/libjvm/issues/281#issuecomment-1519177515) doesn't sound uncommon to me and baking the `ca` into the image seems a bit unnecessary to me.
3. Option 1 would only solve some use cases and option 2 should solve all, right?
