### ISSUE TITLE
Provide an option to use run image with preinstalled JRE/JVM

### ISSUE THREAD

**Issue by vkochnev** [paketo-buildpacks/libjvm#31]
Can you provide an option to use run image with preinstalled Java?
This will allow to use security team pre-approved base images with Java.
Now we cannot actually make use of buildpacks.

**Comment by nebhale** [comment]
@vkochnev Thanks for your request.  Unfortunately, supporting pre-installed JVMs isn't in the spirit of the Cloud Native Buildpacks project and therefore we won't be doing this.

To give you a little context, Stacks (the base image analog for Cloud Native Buildpacks) should [only provide ABI-compatible software](https://github.com/buildpacks/spec/blob/main/platform.md#compatibility-guarantees).  The JVM has never been (and admittedly never claimed to be) ABI compatible between releases.  Therefore it is unsafe for us to [rebase](https://github.com/buildpacks/spec/blob/main/platform.md#rebase) an application's image that has a JVM in it without retesting the entire thing from scratch.

We prove Cloud Native Buildpacks for a number of popular JVM distributions

- [AdoptOpenJDK](https://github.com/paketo-buildpacks/adopt-openjdk)
- [Amazon Corretto](https://github.com/paketo-buildpacks/amazon-corretto)
- [Azul Zulu](https://github.com/paketo-buildpacks/azul-zulu)
- [BellSoft Liberica](https://github.com/paketo-buildpacks/bellsoft-liberica)
- [Eclipse OpenJ9](https://github.com/paketo-buildpacks/eclipse-openj9)
- [GraalVM](https://github.com/paketo-buildpacks/graalvm)
- [SapMachine](https://github.com/paketo-buildpacks/sap-machine)

and if there is another OpenJDK-based freely distributable distribution that you'd like us to support, please feel free to open an issue about it.  If you can't use one of the seven current distributions, you'd be better off creating your own buildpack to provide the enterprise sanctioned binaries you can use.  `libjvm` does the heavy lifting and If you look at [`BellSoft Liberica`] for example, you'll find that the entire buildpack code is contained in a [single Golang file](https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/cmd/main/main.go#L27-L32) and a [list of dependencies](https://github.com/paketo-buildpacks/bellsoft-liberica/blob/main/buildpack.toml#L58-L140).

**Comment by vkochnev** [comment]
@nebhale I understand the rationale and appreciate your explanation. Creation of a custom buildpack definitely doesn't look too difficult and we will check if it is worth investing in this. Or maybe we'll use another approach. Thanks!

**Comment by nebhale** [comment]
@vkochnev Please keep in touch and let us know either how it goes or how we can help you.  As you can see, it’s not a technical issue (we’d have already done it if it was!), but a philosophical one.  We work with many enterprises that have these kinds of requirements and I’m interested in hearing what ended up being acceptable for yours.
