### ISSUE TITLE
Question: owner and permission of injected JRE

### ISSUE THREAD

**Issue by petermylemans** [paketo-buildpacks/libjvm#32]
When trying to figure out how buildpacks work I stumbled upon the fact that the JRE native layer is owned by 1000:1000. Same with the final application jar and class files.

In my own manually crafted containers and in a more classic Linux deployment (in e.g. /opt folder), I've always had the habit of making these owned by root but readable/executable by the everybody. That way the runtime user can execute the application; but not modify its source files.

Is this by design this way? It feels less secure from a container hardening point of view, but I'm not an expert.

**Comment by ekcasey** [comment]
We think the most secure way to ensure that the application does not modify its source file is to run the entire container with a read-only root filesystem (and mount a writable `/tmp` dir). This [blog post](https://blog.atomist.com/security-of-docker-kubernetes/) describes how to do this in `docker` and k8s.

The fact that these directories are owned by the application user are an artifact of hardening in the build process (the buildpacks themselves run as an unprivileged user). We could theoretically introduce features in the CNB spec that would allow an unprivileged buildpack to indicate that the files in a given layer should be exported with root ownership, but making the entire root filesystem readonly seems like the simpler/safer option.
