### ISSUE TITLE
Reproducible builds with spring boot: Different image names result in different image IDs

### ISSUE THREAD

**Issue by schnatterer** [paketo-buildpacks/libjvm#37]
**Preface**
This issue is about building spring boot images but I'm not sure which build pack actually causes my issue, so I'm posting it here in the builder. Please move this issue, if it fits better somewhere else.

**Actual issue**

* I'm looking for ways to get deterministic builds for spring boot projects using build packs. 
* I've worked out so far that my best bet is to pin the builder image's repo digest.
* With a builder image from August 2020 this works as expected. That is, whenever I build the same code, the resulting image ID is the same.
* With the latest builder image this no longer works. That is, building the same code results in a new image ID when different image names are set.

Here's an example:

```
# Just get some project to build
cd /tmp
wget -O demo.zip https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=2.3.5.RELEASE&baseDir=demo&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&packaging=jar&javaVersion=11
unzip demo.zip
cd demo

# Unexpected: Building the same code but using different image names (created with the latest builder image, uploaded November 7 2020): Different image IDs
BUILDER=gcr.io/paketo-buildpacks/builder@sha256:bae0a6b7ec5d51867eb49ac598775bb5fa8788bba458d2edfda314611be554a8
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s) -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s) -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'

[INFO]     [creator]     *** Images (b20d54746b9a):
[INFO]     [creator]           docker.io/library/1604994725:latest
[INFO]     [creator]     *** Images (1992ec6cbc31):
[INFO]     [creator]           docker.io/library/1604994755:latest

# Same image, when image name is the same
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=1 -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=1 -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'

[INFO]     [creator]     *** Images (3c57885e2200):
[INFO]     [creator]           docker.io/library/1:latest
[INFO]     [creator]     *** Images (3c57885e2200):
[INFO]     [creator]           docker.io/library/1:latest
```

So my workaround would be to use the same image name for an application on each build. But this has a downside: When building multiple branches of the same application on the same machine (e.g. CI server) at the same time, they might overwrite the image name resulting in the wrong images being pushed. 

Also
* the `imageName` AKA docker tag is only a tag. One image can have multiple tags. The image is uniquely identified by it's content addressable ID, not by its tags. So for me it's unexpected that the image tag changes the ID of the image
* this used to work as expected in the past. Same commands, but different builder image (from august 2020)

```
BUILDER=gcr.io/paketo-buildpacks/builder@sha256:4d77f1f574148ff8f6fcd6ada7bf16559aa9ab080c30cdfc6613cdb235c0fb3b
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s) -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s) -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'
[INFO]     [creator]     *** Images (c0707e59e6ca):
[INFO]     [creator]           docker.io/library/1604994412:latest
[INFO]     [creator]     *** Images (c0707e59e6ca):
[INFO]     [creator]           docker.io/library/1604994465:latest
```

Any ideas which change (between august to november) caused this change in behavior?

**Comment by schnatterer** [comment]
Thanks very much for the fixes!
Can you estimate when they will be available via the `gcr.io/paketo-buildpacks/builder:base-platform-api-0.3` image? 
The [one published yesterday](https://console.cloud.google.com/gcr/images/paketo-buildpacks/GLOBAL/builder@sha256:9de1015aae69197446da778eed2236327c71e71f2451d8e939a1a6fef042dd2f/) still doesn't yield reproducible builds:

```
BUILDER=gcr.io/paketo-buildpacks/builder@sha256:9de1015aae69197446da778eed2236327c71e71f2451d8e939a1a6fef042dd2f
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s) -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s) -Dspring-boot.build-image.builder=$BUILDER | grep -A1 '*** Images'

[INFO]     [creator]     *** Images (d9b8d9b4feff):
[INFO]     [creator]           docker.io/library/1605545655:latest
[INFO]     [creator]     *** Images (8e72c3313dea):
[INFO]     [creator]           docker.io/library/1605545690:latest
```

**Comment by nebhale** [comment]
@schnatterer I’ve now done the releases

- [`libjvm` 1.24.2](https://github.com/paketo-buildpacks/libjvm/releases/tag/v1.24.2)
- [`bellsoft-liberica` 5.2.1](https://github.com/paketo-buildpacks/bellsoft-liberica/releases/tag/v5.2.1)
- [`java` 4.3.0](https://github.com/paketo-buildpacks/java/releases/tag/v4.3.0)

and while I haven’t verified it directly, I believe [`base` 0.1.17`](https://github.com/paketo-buildpacks/base-builder/releases/tag/v0.1.17) is now available with your fixes in it.

**Comment by schnatterer** [comment]
Thanks @nebhale. 
I can confirm that my issue is resolved in `gcr.io/paketo-buildpacks/builder:0.1.17-base`.

BTW are the tags like `0.1.17-base` a good choice for reproducible builds (i.e. are they pushed only once) or is it better to stick with repo digests?

```
BUILDER=gcr.io/paketo-buildpacks/builder:0.1.17-base
 ./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s) | grep -A1 '*** Images' 
./mvnw clean spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$(date +%s)  | grep -A1 '*** Images'

[INFO]     [creator]     *** Images (aba7670e8339):
[INFO]     [creator]           docker.io/library/1605610105:latest
[INFO]     [creator]     *** Images (aba7670e8339):
[INFO]     [creator]           docker.io/library/1605610163:latest
``

**Comment by nebhale** [comment]
@schnatterer I guess it depends on trust really.  We don't ever overwrite tags, but Docker doesn't actively prevent (or notify when it does happen) like Git does.  So if you trust us, tag names are a much easier way for us to describe when changes are propagated.  But if you don't trust us, then hashes are the only true truth in registries.  We're sympathetic to both views which is why our [release notes](https://github.com/paketo-buildpacks/java/releases/tag/v4.3.0) include both.

**Comment by schnatterer** [comment]
@nebhale thanks for elaborating.
I agree, tag names are just much easier to maintain, which is exactly why I ask. 
In general, I'm willing to trust, if I know that tags are generally not overwritten. Some tags, like `base-platform-api-0.3` are overwritten, though. So I thought I better ask before having to find out the hard way.
Thanks for your ongoing support and until next time :wink:
