### ISSUE TITLE
Trivial minor issue | A confirmation log of having written successfully the `dns cache ttl` setting in JVM setting file must get printed only after it has successfully done so and not before.

### ISSUE THREAD

**Issue by hkiiita** [paketo-buildpacks/libjvm#418]
## Issue: Confirmation Log Order

https://github.com/paketo-buildpacks/libjvm/blob/main/helper/link_local_dns.go#L54
In the Execute function of the LinkLocalDNS type, the log message indicating that JVM DNS caching has been disabled is printed before the function has successfully written the changes to the JVM settings file. The confirmation log should only be printed after successfully writing to the file.

## Expected Behavior
The confirmation log message should only be printed after the DNS settings have been successfully written to the file. If an error occurs while opening or writing to the file, the function should not log the confirmation message and should instead return an appropriate error.

## Current Behavior
The function logs ```l.Logger.Info("JVM DNS caching disabled in favor of link-local DNS caching")``` before ensuring that the DNS settings have been correctly written to the specified file. This log message may appear even if the file write operation fails.

**Comment by hkiiita** [comment]
Awaited discussion on this , if any. But its been too long that the issue has remained open, hence , i have also opened a PR corresponding to it assuming maintainers may want to comment on the PR itself. 

https://github.com/paketo-buildpacks/libjvm/pull/439

**Comment by dmikusa** [comment]
Resolved with merge of #439
