### ISSUE TITLE
JDK is not available in subsequent buildpacks

### ISSUE THREAD

**Issue by dmikusa-pivotal** [paketo-buildpacks/libjvm#75]
## What happened?

* What were you attempting to do?
Use the amazon-corretto buildpack

* What did you expect to happen?
The jdk should be available to all buildpacks after amazon-corretto. 

* What was the actual behavior? Please provide log output, if possible.

There are two layers: "jdk" and "jre". Normally, they have two different names, but in this case they end up both being "jdk".

The first layer metadata looks like:

```
Writing layer metadata: /layers/paketo-buildpacks_amazon-corretto/jdk.toml <= {LayerTypes:{Build:true Cache:true Launch:false} Metadata:map[cert-file:333e611c066ee34adefa78c4f1f3fa710a7f50ffa5fbd2fd53987b2336feaa13 dependency:map[id:jdk licenses:[map[type:GPL-2.0 WITH Classpath-exception-2.0 uri:https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source]] name:Corretto JDK sha256:0de91aef7136254753c04a8f3ec81b3d3f1cb736004046fc46bddbc783112129 stacks:[io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3] uri:https://corretto.aws/downloads/resources/11.0.11.9.1/amazon-corretto-11.0.11.9.1-linux-x64.tar.gz version:11.0.11]] Name:jdk Path:/layers/paketo-buildpacks_amazon-corretto/jdk BuildEnvironment:map[JAVA_HOME.override:/layers/paketo-buildpacks_amazon-corretto/jdk JDK_HOME.override:/layers/paketo-buildpacks_amazon-corretto/jdk] LaunchEnvironment:map[] SharedEnvironment:map[] Profile:map[] Exec:{Path:/layers/paketo-buildpacks_amazon-corretto/jdk/exec.d}}
```

The second layer is added and it looks like this:

```
Writing layer metadata: /layers/paketo-buildpacks_amazon-corretto/jdk.toml <= {LayerTypes:{Build:false Cache:false Launch:true} Metadata:map[cert-file:333e611c066ee34adefa78c4f1f3fa710a7f50ffa5fbd2fd53987b2336feaa13 dependency:map[id:jdk licenses:[map[type:GPL-2.0 WITH Classpath-exception-2.0 uri:https://aws.amazon.com/corretto/faqs/#Licensing_and_Open_Source]] name:Corretto JDK sha256:0de91aef7136254753c04a8f3ec81b3d3f1cb736004046fc46bddbc783112129 stacks:[io.buildpacks.stacks.bionic org.cloudfoundry.stacks.cflinuxfs3] uri:https://corretto.aws/downloads/resources/11.0.11.9.1/amazon-corretto-11.0.11.9.1-linux-x64.tar.gz version:11.0.11]] Name:jdk Path:/layers/paketo-buildpacks_amazon-corretto/jdk BuildEnvironment:map[] LaunchEnvironment:map[] SharedEnvironment:map[] Profile:map[] Exec:{Path:/layers/paketo-buildpacks_amazon-corretto/jdk/exec.d}}
```

Note how the layer names are the same but the LayerTypes are different. It looks like the LayerTypes from the second layer are now overwriting the previous metadata. Thus the JDK isn't available at build time for subsequent buildpacks to use.

This is likely due to the lifecycle API 0.6 upgrade.

## Build Configuration

Run `pack build apps/maven -v -e BP_DEBUG=true --builder paketobuildpacks/builder:base --buildpack gcr.io/paketo-buildpacks/amazon-corretto --buildpack gcr.io/paketo-buildpacks/java`

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

* What buildpacks are you using? Please include versions.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by ekcasey** [comment]
Seems like in this case, when we are using a JDK at both build and runtime, we want a single layer where `build`, `cache` and `launch` are all true.
