### ISSUE TITLE
Memory calculation on AWS ECS Fargate does not work properly

### ISSUE THREAD

**Issue by kschlesselmann** [paketo-buildpacks/libjvm#86]
It seems that ECS Fargate does not report task memory constraints by some means that are properly picked up by the memory calculator.

I've set up my task to have e.g. 8G memory but during startup of my services I get random values in my log messages that exceed the limits. For example
```
Calculating JVM memory based on 15637632K available memory
```

If https://serverfault.com/questions/1035465/why-would-aws-fargate-task-containers-report-wildly-incorrect-memory-limits is still correct it seems that
> … The explanation from AWS Support is that the containers are reporting the size of their host machine. …

Is there a way to define the maximum available memory yourself and let the calculator work with this value?

Our images are built by the Spring Boot gradle plugin without any customizations. Here is an example build log:
```
11:48:57  > Task :bootBuildImage
11:48:57  Building image 'docker.io/library/rules:2.49.21'
11:48:57  
11:48:57   > Pulling builder image 'docker.io/paketobuildpacks/builder:base' ..................................................
11:48:57   > Pulled builder image 'paketobuildpacks/builder@sha256:4fae5e2abab118ca9a37bf94ab42aa17fef7c306296b0364f5a0e176702ab5cb'
11:48:58   > Pulling run image 'docker.io/paketobuildpacks/run:base-cnb' ..................................................
11:48:58   > Pulled run image 'paketobuildpacks/run@sha256:8ee09c6154a8c9a99f5da07c317102f5c29ad9b1bf2b7742799eb51d9f1a2e56'
11:48:58   > Executing lifecycle version v0.11.4
11:48:58   > Using build cache volume 'pack-cache-8d5faa8a7ebe.build'
11:48:58  
11:48:58   > Running creator
11:49:00      [creator]     ===> DETECTING
11:49:00      [creator]     5 of 18 buildpacks participating
11:49:00      [creator]     paketo-buildpacks/ca-certificates   2.3.2
11:49:00      [creator]     paketo-buildpacks/bellsoft-liberica 8.2.0
11:49:00      [creator]     paketo-buildpacks/executable-jar    5.1.2
11:49:00      [creator]     paketo-buildpacks/dist-zip          4.1.2
11:49:00      [creator]     paketo-buildpacks/spring-boot       4.4.2
11:49:00      [creator]     ===> ANALYZING
11:49:00      [creator]     Previous image with name "docker.io/library/rules:2.49.21" not found
11:49:00      [creator]     ===> RESTORING
11:49:00      [creator]     ===> BUILDING
11:49:00      [creator]     
11:49:00      [creator]     Paketo CA Certificates Buildpack 2.3.2
11:49:00      [creator]       https://github.com/paketo-buildpacks/ca-certificates
11:49:00      [creator]       Launch Helper: Contributing to layer
11:49:00      [creator]         Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
11:49:00      [creator]     
11:49:00      [creator]     Paketo BellSoft Liberica Buildpack 8.2.0
11:49:00      [creator]       https://github.com/paketo-buildpacks/bellsoft-liberica
11:49:00      [creator]       Build Configuration:
11:49:00      [creator]         $BP_JVM_VERSION              16.*            the Java version
11:49:00      [creator]       Launch Configuration:
11:49:00      [creator]         $BPL_JVM_HEAD_ROOM           0               the headroom in memory calculation
11:49:00      [creator]         $BPL_JVM_LOADED_CLASS_COUNT  35% of classes  the number of loaded classes in memory calculation
11:49:00      [creator]         $BPL_JVM_THREAD_COUNT        250             the number of threads in memory calculation
11:49:00      [creator]         $JAVA_TOOL_OPTIONS                           the JVM launch flags
11:49:00      [creator]       BellSoft Liberica JRE 16.0.2: Contributing to layer
11:49:00      [creator]         Downloading from https://github.com/bell-sw/Liberica/releases/download/16.0.2+7/bellsoft-jre16.0.2+7-linux-amd64.tar.gz
11:49:03      [creator]         Verifying checksum
11:49:03      [creator]         Expanding to /layers/paketo-buildpacks_bellsoft-liberica/jre
11:49:06      [creator]         Adding 129 container CA certificates to JVM truststore
11:49:07      [creator]         Writing env.launch/BPI_APPLICATION_PATH.default
11:49:07      [creator]         Writing env.launch/BPI_JVM_CACERTS.default
11:49:07      [creator]         Writing env.launch/BPI_JVM_CLASS_COUNT.default
11:49:07      [creator]         Writing env.launch/BPI_JVM_SECURITY_PROVIDERS.default
11:49:07      [creator]         Writing env.launch/JAVA_HOME.default
11:49:07      [creator]         Writing env.launch/MALLOC_ARENA_MAX.default
11:49:07      [creator]       Launch Helper: Contributing to layer
11:49:07      [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/active-processor-count
11:49:07      [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/java-opts
11:49:07      [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/link-local-dns
11:49:07      [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/memory-calculator
11:49:07      [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/openssl-certificate-loader
11:49:07      [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/security-providers-configurer
11:49:07      [creator]         Creating /layers/paketo-buildpacks_bellsoft-liberica/helper/exec.d/security-providers-classpath-9
11:49:07      [creator]       JVMKill Agent 1.16.0: Contributing to layer
11:49:07      [creator]         Downloading from https://github.com/cloudfoundry/jvmkill/releases/download/v1.16.0.RELEASE/jvmkill-1.16.0-RELEASE.so
11:49:07      [creator]         Verifying checksum
11:49:07      [creator]         Copying to /layers/paketo-buildpacks_bellsoft-liberica/jvmkill
11:49:07      [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.append
11:49:07      [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.delim
11:49:07      [creator]       Java Security Properties: Contributing to layer
11:49:07      [creator]         Writing env.launch/JAVA_SECURITY_PROPERTIES.default
11:49:07      [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.append
11:49:07      [creator]         Writing env.launch/JAVA_TOOL_OPTIONS.delim
11:49:07      [creator]     
11:49:07      [creator]     Paketo Executable JAR Buildpack 5.1.2
11:49:07      [creator]       https://github.com/paketo-buildpacks/executable-jar
11:49:07      [creator]       Class Path: Contributing to layer
11:49:07      [creator]         Writing env/CLASSPATH.delim
11:49:07      [creator]         Writing env/CLASSPATH.prepend
11:49:07      [creator]       Process types:
11:49:07      [creator]         executable-jar: java org.springframework.boot.loader.JarLauncher (direct)
11:49:07      [creator]         task:           java org.springframework.boot.loader.JarLauncher (direct)
11:49:07      [creator]         web:            java org.springframework.boot.loader.JarLauncher (direct)
11:49:07      [creator]     
11:49:07      [creator]     Paketo Spring Boot Buildpack 4.4.2
11:49:07      [creator]       https://github.com/paketo-buildpacks/spring-boot
11:49:07      [creator]       Creating slices from layers index
11:49:07      [creator]         dependencies
11:49:07      [creator]         spring-boot-loader
11:49:07      [creator]         snapshot-dependencies
11:49:07      [creator]         application
11:49:07      [creator]       Launch Helper: Contributing to layer
11:49:07      [creator]         Creating /layers/paketo-buildpacks_spring-boot/helper/exec.d/spring-cloud-bindings
11:49:07      [creator]       Spring Cloud Bindings 1.7.1: Contributing to layer
11:49:07      [creator]         Downloading from https://repo.spring.io/release/org/springframework/cloud/spring-cloud-bindings/1.7.1/spring-cloud-bindings-1.7.1.jar
11:49:08      [creator]         Verifying checksum
11:49:08      [creator]         Copying to /layers/paketo-buildpacks_spring-boot/spring-cloud-bindings
11:49:08      [creator]       Web Application Type: Contributing to layer
11:49:08      [creator]         Reactive web application detected
11:49:08      [creator]         Writing env.launch/BPL_JVM_THREAD_COUNT.default
11:49:08      [creator]       4 application slices
11:49:08      [creator]       Image labels:
11:49:08      [creator]         org.springframework.boot.version
11:49:08      [creator]     ===> EXPORTING
11:49:08      [creator]     Adding layer 'paketo-buildpacks/ca-certificates:helper'
11:49:08      [creator]     Adding layer 'paketo-buildpacks/bellsoft-liberica:helper'
11:49:08      [creator]     Adding layer 'paketo-buildpacks/bellsoft-liberica:java-security-properties'
11:49:10      [creator]     Adding layer 'paketo-buildpacks/bellsoft-liberica:jre'
11:49:10      [creator]     Adding layer 'paketo-buildpacks/bellsoft-liberica:jvmkill'
11:49:10      [creator]     Adding layer 'paketo-buildpacks/executable-jar:classpath'
11:49:10      [creator]     Adding layer 'paketo-buildpacks/spring-boot:helper'
11:49:10      [creator]     Adding layer 'paketo-buildpacks/spring-boot:spring-cloud-bindings'
11:49:10      [creator]     Adding layer 'paketo-buildpacks/spring-boot:web-application-type'
11:49:10      [creator]     Adding 5/5 app layer(s)
11:49:10      [creator]     Adding layer 'launcher'
11:49:10      [creator]     Adding layer 'config'
11:49:10      [creator]     Adding layer 'process-types'
11:49:10      [creator]     Adding label 'io.buildpacks.lifecycle.metadata'
11:49:10      [creator]     Adding label 'io.buildpacks.build.metadata'
11:49:10      [creator]     Adding label 'io.buildpacks.project.metadata'
11:49:10      [creator]     Adding label 'org.springframework.boot.version'
11:49:10      [creator]     Setting default process type 'web'
11:49:10      [creator]     Saving docker.io/library/rules:2.49.21...
11:49:14      [creator]     *** Images (32aeb1b16339):
11:49:14      [creator]           docker.io/library/rules:2.49.21
11:49:18  
11:49:18  Successfully built image 'docker.io/library/rules:2.49.21'
```

**Comment by dmikusa-pivotal** [comment]
There is no way to configure the memory limit. The calculator will pull that from cgroup information exposed to the container. If your provider isn't exposing that information properly, there's not a lot you can do except ask them to expose the proper numbers. 

For what it's worth, we do have a [PR that's to be merged soon with support for cgroup v2](https://github.com/paketo-buildpacks/libjvm/pull/83). I don't know if this will help in your case, but I thought I'd mention it. You could look at these two files, the second being for the v2 support, and see if either reports the correct memory limit.

```
/sys/fs/cgroup/memory/memory.limit_in_bytes
/sys/fs/cgroup/memory.max
```

**Comment by kschlesselmann** [comment]
Hi @dmikusa-pivotal

It seems that `/sys/fs/cgroup/memory.max` does not exist and `/sys/fs/cgroup/memory/memory.limit_in_bytes` contains 9223372036854771712. It doesn't look so promising.

What about something like providing an environment variable as a global override and then some logic like
```
if (env.isSet()) 
    totalMemory = env.value()
else
    totalMemory = useCurrentMechanism()
```
That way we could support all platforms that behave weird and if you do nothing everything stays as is? Providing this variable would be no issue in an IaC setup since you specify the value nevertheless ;-)

**Comment by dmikusa-pivotal** [comment]
The issue with making this user-configurable is that you're effectively allowing users to disable the memory calculator, or at the very least lie to it and compromise its functionality. The memory calculator provides a lot of upfront integrity checks, which help to ensure Java apps will run and will continue running overtime. There's [a thread here with more background about why we feel the memory calculator should not be something users can bypass](https://github.com/paketo-buildpacks/java-azure/issues/208).

Right now what's happening is that the cgroup info isn't present, so we're falling back to reading `/proc/meminfo` which has the total VM memory size. That's where the `Calculating JVM memory based on 15637632K available memory` message comes from.

What I'd prefer to do is to work with information present in the system. Is there any place where the AWS service exposes the actual memory limit to you? We could easily make the memory calculator check this also.

**Comment by kschlesselmann** [comment]
Hm, I'd have to have a look at the following endpoints but it seems that there are metadata endpoints you could query: https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html

A HTTP GET to `${ECS_CONTAINER_METADATA_URI_V4}/task` should (among others) return `.Limits.Memory` (seems to be in MB).

**Comment by dmikusa-pivotal** [comment]
Ah, perfect. Thanks for the link. I think we can make that work. If that env variable is set, we can query the API & pull back the memory limit.

**Comment by kschlesselmann** [comment]
I just tested the endpoint with one of our services:
```
"Limits": {
        "CPU": 4,
        "Memory": 8192
    },
```
for a service configured with 8G of memory. Looks fine to me :-)

**Comment by kschlesselmann** [comment]
If I think about it again my proposed solution is probably only valid in our case since we run one container in every task. There's `.Containers[].Limits.Memory` as well but you'd have to detect the proper container in this list.

Looking at the task would be fine as a first step though I think.

Is there anything we could do in the meantime? Some services are really unstable because of wrong memory settings :-(

**Comment by dmikusa-pivotal** [comment]
> If I think about it again my proposed solution is probably only valid in our case since we run one container in every task. There's `.Containers[].Limits.Memory` as well but you'd have to detect the proper container in this list.
> 
> Looking at the task would be fine as a first step though I think.

I don't have any experience with AWS ECS Fargate so I will defer to you on what you think is best here. It's not really much harder to pull from `.Containers[].Limits.Memory`, but we'd just need to have a way to know the container that we're currently running in. Not sure if there is an env variable or way we can pull that information in the container. I think we'd need that otherwise, we'd have to use `.Limits.Memory` instead.

> Is there anything we could do in the meantime? Some services are really unstable because of wrong memory settings :-(

Hmm, one thought. If the memory calculator is consistently detecting that there is 16G of RAM available, but there is really only 8G available, you could probably set the `BPL_JVM_HEADROOM` env variable at runtime. That will tell the memory calculator to set aside some percent of the detected memory. You could try setting that to 50 (ie. 50%). The memory calculator should then set up memory as if there is only 8G total which should fit within the actual limit of your container.

>>Configure the percentage of headroom the memory calculator will allocated. Defaults to 0.

Another thought would be to completely take control of the JVM memory configuration. You can set the env variable `JAVA_TOOL_OPTIONS` and just override all of the JVM memory settings that the memory calculator is setting (i.e. `-Xmx`, `-Xms`, ...). The calculator conveniently prints the list of what settings it's using, so you can copy, adjust and paste those into `JAVA_TOOL_OPTIONS` (you might start with just `-Xmx and -Xms`, cause after a certain point memory calculator just assigns whatever's left to the heap and I think 8G is large enough where you're past that limit). The memory calculator will defer to what you set, so you should be able to set values that keep the app running within the actual memory limit. 

Both of these ideas assume that the container is unstable because the memory calculator is picking the wrong limits, your app is exceeding the container memory limit and the container orchestrator is killing it. If it's unstable for another reason, these options probably won't help.

Hope that helps!

**Comment by kschlesselmann** [comment]
`BPL_JVM_HEADROOM` is no option sadly since the memory is not constant. It seems to vary somewhere between 16G and 32G. I'll have a look at the custom JVM memory settings then.

I opened a support case with AWS in parallel to see what's their opinion on this.

Regarding global limits vs container limits I think the container limit would be the first place to look and then the global limit as a fallback (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_memory).

The metadata API documentation contains an example response. It seems that you could use `.Containers[].Image` or `.Containers.ImageID` to detect the proper entry. I don't know if you have those two available at runtime in the calculator?

**Comment by kschlesselmann** [comment]
@dmikusa-pivotal New insights from the AWS support. We've been using ECS "wrong" the whole time. If you specify the limits on the [container definition](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_memory) as well everything works like a charm.

At least I hope that this issue helps someone else ;-)

**Comment by dmikusa-pivotal** [comment]
Oh, very interesting. Thanks for the feedback!
